### PR TITLE
* Added support for dynamic attributes on a Jsp tag

### PR DESCRIPTION
**Pull request by tkvw**
* Added support for dynamic attributes on a Jsp tag

### CODE REVIEW

**Comment by tkvw** [comment]
Fixes issue https://github.com/grails/grails-gsp/issues/2

**Comment by graemerocher** [comment]
Any chance of providing a test? You can see examples of tests here https://github.com/grails/grails-gsp/blob/master/grails-plugin-gsp/src/test/groovy/org/grails/gsp/jsp/GroovyPageWithJSPTagsTests.groovy

**Comment by tkvw** [comment]
It was more difficult then I expected, the build.gradle depedency graph did not include the project grails-web-jsp so the test did not pickup the changed version :S
But the test is added now.

**Comment by graemerocher** [comment]
Thanks!

**Pull request merged**
