### PR TITLE
6.2.x to 7.0.x merge

### PR DESCRIPTION
**Pull request by jdaugherty**

### CODE REVIEW

**Comment by jdaugherty** [comment]
Merges 6.2.x into 7.0.x - we should have zero files changed.

**Review by jamesfredley — APPROVED** [review]

**Comment by codeconsole** [comment]
no longer needed

**Comment by jdaugherty** [comment]
@codeconsole  you'll need to force push 6.2.x otherwise when we merge a branch off of 6.2.x in the future, the revert will be applied to the 7.0.x branch.

**Comment by codeconsole** [comment]
@jdaugherty it was already done when I closed the ticket 👍

**Pull request closed without merging**
