### PR TITLE
Avoid update…

### PR DESCRIPTION
**Pull request by pharrup**
…s of meta class in production

### CODE REVIEW

**Comment by puneetbehl** [comment]
Please sign the CLA

**Comment by JasonTypesCodes** [comment]
I've been digging into this, and after some further investigation, I think the logic as it is expressed before this change is correct.  

What I believe should be happening, is that in non-development environments as NamespaceDispatchers are identified, they are added to the ExpandoMetaClass of the taglib so that in future calls the `propertyMissing` method isn't required.

In practice, while the property is set on the ExpandoMetaClass, the instance of the taglib isn't seeing that update and subsequent attempts to access the same property are still going into the propertyMissing.  It seems that making any change to the MetaClass of the tag lib instance also brings with it the other updates made to the ExpandoMetaClass for the class and in subsequent calls `propertyMissing` is not called.  I'll submit an issue for this and I'm testing out some potential fixes

**Review by JasonTypesCodes — CHANGES_REQUESTED** [review]
I don't feel this is the right approach, but it helped identify a different issue

**Comment by JasonTypesCodes** [comment]
I've created an issue for this problem here: https://github.com/grails/grails-gsp/issues/314 I'll put together a proposed solution and open a fresh PR with that for review.

**Comment by JasonTypesCodes** [comment]
Alternate PR: https://github.com/grails/grails-gsp/pull/315

**Pull request closed without merging**
