### PR TITLE
Create new Compiler Task that can be Forked from Gradle

### PR DESCRIPTION
**Pull request by davydotcom**
GSP Still uses ANT inside the groovy daemon for compiling. This causes huge performance issues when compiling a large amount of classes. This is now forked using the GroovyPageCompilerForkTask...grails PR to follow"
[patch-forked-compile-task 943c2aa8b7] GSP Still uses ANT inside the groovy daemon for compiling. This causes huge performance issues when compiling a large amount of classes. This is now forked using the GroovyPageCompilerForkTask...grails PR to follow

### CODE REVIEW

**Comment by graemerocher** [comment]
Might want to cleanup the commented out code. If it is not necessary anymore it shouldn't be there

**Comment by davydotcom** [comment]
Agreed, I was waiting to be sure you guys were ok with removing the debug logs as the fork seems to output ALL logs

**Comment by davydotcom** [comment]
Added Multithreaded support with a ThreadPool...Improved compile time performance by ~40%

**Comment by puneetbehl** [comment]
@davydotcom I am not sure if I understand why the debug logs are removed? Does it print all logs irrespective of the Logger configuration? 

Personally, I find logs very helpful while debugging. 

Thanks!

**Comment by davydotcom** [comment]
yes it does...this is why grails-views also has no Logger use because a forked config tends to do that. Also several of these arent really needed.

**Pull request merged**
