### PR TITLE
fix detection of FilterChainProxy bean presence…

### PR DESCRIPTION
**Pull request by bkoehm**
…such that a NoSuchBeanDefinitionException isn't thrown if the class resolves but the bean doesn't exist

### CODE REVIEW

**Comment by codeconsole** [comment]
You have Spring Security in your class path, but are not using it?

**Comment by codeconsole** [comment]
@bkoehm I can't replicate the problem

https://github.com/codeconsole/demo-622-to-7

I don't understand why you have FilterChainProxy in your class path, but don't have a filterChain?

**Comment by bkoehm** [comment]
@codeconsole I'm encountering it in a unit test that implements `grails.testing.web.taglib.TagLibUnitTest` from grails-web-testing-support.  The unit test calls `applyTemplate()`.  This unit test runs within a project that has spring-security as a dependency.

**Comment by bkoehm** [comment]
Relevant part of a stacktrace of failing test:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.grails.plugins.web.taglib.FormTagLib': No qualifying bean of type 'org.springframework.security.web.FilterChainProxy' available
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1272)
	at org.grails.taglib.TagLibraryLookup.putTagLib(TagLibraryLookup.java:141)
	at org.grails.testing.runtime.support.LazyTagLibraryLookup.putTagLib(LazyTagLibraryLookup.java:105)
	at org.grails.taglib.TagLibraryLookup.registerTagLib(TagLibraryLookup.java:113)
	at org.grails.taglib.TagLibraryLookup.registerTagLib(TagLibraryLookup.java:92)
	at org.grails.testing.runtime.support.LazyTagLibraryLookup.lookupTagLibrary(LazyTagLibraryLookup.java:91)
	at grails.artefact.gsp.TagLibraryInvoker$Trait$Helper.methodMissing(TagLibraryInvoker.groovy:80)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at edu.berkeley.ui.BootstrapExtrasTagLib.methodMissing(BootstrapExtrasTagLib.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:924)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1413)
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1335)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1088)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:645)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:391)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:328)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at edu.berkeley.ui.BootstrapExtrasTagLib$_closure1.doCall(BootstrapExtrasTagLib.groovy:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.Closure.call(Closure.java:433)
	at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:446)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:364)
	... 64 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.security.web.FilterChainProxy' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:373)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:364)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1290)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at org.grails.plugins.web.taglib.FormTagLib.afterPropertiesSet(FormTagLib.groovy:81)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1849)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1798)
	... 107 more
```

**Comment by codeconsole** [comment]
ok, well if that is the case, I would prefer to just ignore the exception.  Does this work for you?
https://github.com/grails/grails-gsp/pull/550

**Comment by bkoehm** [comment]
Yep, works for me.

**Pull request closed without merging**
