### PR TITLE
gsp-plugin-param-issue-11087

### PR DESCRIPTION
**Pull request by niravassar**
From issue https://github.com/grails/grails-core/issues/11087

@jameskleeh The scenario here (calling `resolveViewInBinaryPlugin`_ is specific to a plugin so I thought it would be easier to just alter the existing code.  `createGroovyPageCompiledScriptSource` is only used in one other place so I added a parameter for a plugin to it. 

The code `findReloadablePage` attemptes to reuse the existing code `findResource` and `findResourceInPugins`. The need is to not look for resources in the application because we want to look for resources in the plugin. So i simply skipped that when a plugin is passed in.

### CODE REVIEW

**Comment by jameskleeh** [comment]
@niravassar This is wrong because the plugin is not taken into consideration. `findResourceInPlugins(uri);` is called, even though we want to target a specific plugin.

**Comment by niravassar** [comment]
Just some notes:

maybe in this scenario we dont even need to call this  `createGroovyPageCompiledScriptSource` this at all

assarn [1:12 PM]
if i just take out the call to `createGroovyPageCompiledScriptSource` we dont even nee dto try and reload and it works
you dont get into this situation of looking with a similar uri for both app and plugin, thus getting into a repeated call over and over. And you avoid this skipping logic that i put in place, along with the looping through binary plugins.  That code i put in works also, but all we are doing is avoiding to try and reload with binary plugins, and looping for no reason

**Comment by niravassar** [comment]
The scenario where the recursive calls to the same uri is solved with the last checkin.

I tested the inline plugin for hot load and it does not work with the code change, AS WELL AS the baseline 3.3.8 code as is. It seems to not work with the original code and must be a lingering issue outside of this bug

**Comment by jameskleeh** [comment]
@niravassar Did you follow http://docs.grails.org/latest/guide/plugins.html#creatingAndInstallingPlugins ?

"Plugins and Multi-Project Builds"

**Pull request merged**
